// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1_r5s8OPrZ5AJIItvlkA2mzLR99MvCKw',
    appId: '1:873664724431:web:f35e6b4b2dd2363db066ba',
    messagingSenderId: '873664724431',
    projectId: 'dbsiswa-cf90c',
    authDomain: 'dbsiswa-cf90c.firebaseapp.com',
    databaseURL: 'https://dbsiswa-cf90c-default-rtdb.firebaseio.com',
    storageBucket: 'dbsiswa-cf90c.firebasestorage.app',
    measurementId: 'G-952XH67S9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9ES9XOuNL52RqETIrSFPFX3i9nHo8EQw',
    appId: '1:873664724431:android:7284059b0f8d2ceeb066ba',
    messagingSenderId: '873664724431',
    projectId: 'dbsiswa-cf90c',
    databaseURL: 'https://dbsiswa-cf90c-default-rtdb.firebaseio.com',
    storageBucket: 'dbsiswa-cf90c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcsh6VM1NUXSqGtnjGolmCgLqOxM7GW1A',
    appId: '1:873664724431:ios:aad090c554fe9325b066ba',
    messagingSenderId: '873664724431',
    projectId: 'dbsiswa-cf90c',
    databaseURL: 'https://dbsiswa-cf90c-default-rtdb.firebaseio.com',
    storageBucket: 'dbsiswa-cf90c.firebasestorage.app',
    iosBundleId: 'com.example.absenSiswa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcsh6VM1NUXSqGtnjGolmCgLqOxM7GW1A',
    appId: '1:873664724431:ios:aad090c554fe9325b066ba',
    messagingSenderId: '873664724431',
    projectId: 'dbsiswa-cf90c',
    databaseURL: 'https://dbsiswa-cf90c-default-rtdb.firebaseio.com',
    storageBucket: 'dbsiswa-cf90c.firebasestorage.app',
    iosBundleId: 'com.example.absenSiswa',
  );

}